AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvironmentName:
    Type: String
  
  CategoryName:
    Type: String
  
  AppName:
    Type: String
  
  Region:
    Type: String
  
Conditions:
  IsDevelopment: !Equals [!Ref EnvironmentName, dev-aws-launchpad]

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        DefaultRootObject: index.html
        Origins:
          - Id: !Sub ${EnvironmentName}-${CategoryName}-${AppName}-s3
            DomainName: !Sub ${EnvironmentName}-${CategoryName}-bucket-${Region}.s3.ap-northeast-1.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt OAC.Id
        DefaultCacheBehavior:
          TargetOriginId: !Sub ${EnvironmentName}-${CategoryName}-${AppName}-s3
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: !If
            - IsDevelopment
            - 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            - 658327ea-f89d-4fab-a63d-7e88639e58f6
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          ViewerProtocolPolicy: redirect-to-https
          
  OAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${EnvironmentName}-${CategoryName}-${AppName}-${Region}-OAC
        Description: Access control for CloudFront to access S3
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4


